---
RANGE: "20160401-20170331"
WORKING_HOURS: "10:00-17:00"
CALENDARS:
  -
    NAME: nomlab
    RANDOM_EVENTS_PER_MONTH: 2
    PARTICIPANT_BORDER: 90
  -
    NAME: swlab
    RANDOM_EVENTS_PER_MONTH: 1
    PARTICIPANT_BORDER: 80
  -
    NAME: university
    RANDOM_EVENTS_PER_MONTH: 0
    PARTICIPANT_BORDER: 100
  -
    NAME: gn
    RANDOM_EVENTS_PER_MONTH: 0
    PARTICIPANT_BORDER: 70
  -
    NAME: new
    RANDOM_EVENTS_PER_MONTH: 0
    PARTICIPANT_BORDER: 60
  -
    NAME: net-mgr
    RANDOM_EVENTS_PER_MONTH: 0
    PARTICIPANT_BORDER: 60
USERS:
  T:
    nomlab: 30
    swlab: 30
    university: 30
    gn : 40
    new: 40
    net-mgr: 30
  M2GN1:
    nomlab: 5
    swlab: 5
    university: 5
    gn : 5
    net-mgr: 5
  M2GN2:
    nomlab: 5
    swlab: 5
    university: 5
    gn : 5
    net-mgr: 5
  M2GN3:
    nomlab: 5
    swlab: 5
    university: 5
    gn : 5
    net-mgr: 5
  M2New1:
    nomlab: 5
    swlab: 5
    university: 5
    new: 5
  M1GN1:
    nomlab: 5
    swlab: 5
    university: 5
    gn : 5
  M1GN2:
    nomlab: 5
    swlab: 5
    university: 5
    gn : 5
    net-mgr: 5
  M1New1:
    nomlab: 5
    swlab: 5
    university: 5
    new: 5
  M1New2:
    nomlab: 5
    swlab: 5
    university: 5
    new: 5
    net-mgr: 5
  M1New3:
    nomlab: 5
    swlab: 5
    university: 5
    new: 5
    net-mgr: 5
  B4GN1:
    nomlab: 5
    swlab: 5
    university: 5
    gn : 5
  B4GN2:
    nomlab: 5
    swlab: 5
    university: 5
    gn : 5
    net-mgr: 5
  B4GN3:
    nomlab: 5
    swlab: 5
    university: 5
    gn : 5
  B4New1:
    nomlab: 5
    swlab: 5
    university: 5
    new: 5
  B4New2:
    nomlab: 5
    swlab: 5
    university: 5
    new: 5
    net-mgr: 5
RECURRENCE:
  -
    SUMMARY: 進捗報告会1
    CALENDAR: nomlab
    DURATION: 120
    TIMING: successively
    INTERVAL: 30
    HOLIDAY: false
    HIDDEN_EVENTS: true
    VACATION_TERM:
      - 8/10-8/14
      - 12/25-1/3
  -
    SUMMARY: 誕生日会
    CALENDAR: nomlab
    INTERVAL: 183
    DURATION: 120
    TIMING:
      - 2/1
      - 9/1
    HOLIDAY: false
    MONTH:
      - 2
      - 3
      - 9
      - 10
    HIDDEN_EVENTS: true
  -
    SUMMARY: 卒業アルバム撮影
    CALENDAR: nomlab
    INTERVAL: 365
    DURATION: 120
    TIMING:
      - 11/1
    HOLIDAY: false
    MONTHWEEK:
      - 11-2
    HIDDEN_EVENTS: true
  -
    SUMMARY: 送別会1
    CALENDAR: nomlab
    INTERVAL: 365
    DURATION: 240
    TIMING:
      - 2/1
    HOLIDAY: false
    MONTHWEEK:
      - 2-4
      - 2-5
      - 3-1
      - 3-2
    HIDDEN_EVENTS: true
    ORDER:
      AFTER:
        - 2/12
      BEFORE:
        - 3/25
  -
    SUMMARY: 研究室大掃除
    CALENDAR: nomlab
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 2/1
    HOLIDAY: false
    MONTHWEEK:
      - 3-4
      - 3-5
    ORDER:
      BEFORE:
        - 4/1
  -
    SUMMARY: 忘年会2
    CALENDAR: nomlab
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 9/1
    HOLIDAY: true
    MONTH:
      - 11
    HIDDEN_EVENTS: true
  -
    SUMMARY: スポーツ大会
    CALENDAR: nomlab
    INTERVAL: 120
    DURATION: 240
    TIMING:
      - 1/15
      - 4/15
      - 9/15
    HOLIDAY: false
    MONTH:
      - 2
      - 5
      - 10
    VACATION_TERM:
      - 8/10-8/14
      - 12/25-1/3
    HIDDEN_EVENTS: true
  -
    SUMMARY: 進捗報告会2
    CALENDAR: swlab
    INTERVAL: 30
    DURATION: 120
    TIMING: successively
    HOLIDAY: false
    HIDDEN_EVENTS: true
    VACATION_TERM:
      - 8/10-8/14
      - 12/25-1/3
  -
    SUMMARY: 忘年会1
    CALENDAR: swlab
    INTERVAL: 365
    DURATION: 240
    TIMING:
      - 11/1
    HOLIDAY: false
    MONTH:
      - 12
    HIDDEN_EVENTS: true
    VACATION_TERM:
      - 8/10-8/14
      - 12/25-1/3
  -
    SUMMARY: M2中間発表
    CALENDAR: swlab
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 11/1
    HOLIDAY: false
    MONTHWEEK:
      - 11-4
      - 11-5
      - 12-1
      - 12-2
  -
    SUMMARY: M1論文紹介
    CALENDAR: swlab
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 9/1
    HOLIDAY: false
    MONTHWEEK:
      - 10-4
      - 10-5
      - 11-1
      - 11-2
  -
    SUMMARY: M2論文紹介
    CALENDAR: swlab
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 6/1
    HOLIDAY: false
    MONTHWEEK:
      - 6-4
      - 6-5
      - 7-1
      - 7-2
  -
    SUMMARY: 暑気払い
    CALENDAR: swlab
    INTERVAL: 365
    DURATION: 240
    TIMING:
      - 6/1
    HOLIDAY: false
    MONTHWEEK:
      - 7-1
      - 7-2
    HIDDEN_EVENTS: true
  -
    SUMMARY: 研修会
    CALENDAR: swlab
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 5/1
    HOLIDAY: false
    MONTHWEEK:
      - 8-4
      - 8-5
      - 9-1
    HIDDEN_EVENTS: true
    ORDER:
      AFTER:
        - 8/20
      BEFORE:
        - 9/4
  -
    SUMMARY: 歓迎会
    CALENDAR: swlab
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 3/1
    HOLIDAY: false
    MONTHWEEK:
      - 4-1
    ORDER:
      AFTER:
        - 4/1
  -
    SUMMARY: 送別会2
    CALENDAR: swlab
    INTERVAL: 365
    DURATION: 240
    TIMING:
      - 2/1
    HOLIDAY: false
    MONTHWEEK:
      - 2-4
      - 2-5
      - 3-1
      - 3-2
    HIDDEN_EVENTS: true
    ORDER:
      AFTER:
        - 2/12
      BEFORE:
        - 3/25
  -
    SUMMARY: レクリエーション
    CALENDAR: swlab
    INTERVAL: 120
    DURATION: 240
    TIMING:
      - 2/1
      - 4/15
      - 9/1
    HOLIDAY: false
    MONTHWEEK:
      - 3-1
      - 3-2
      - 3-3
      - 5-1
      - 5-2
      - 5-3
      - 9-2
      - 9-3
      - 9-4
    HIDDEN_EVENTS: true
  -
    SUMMARY: B4中間発表
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 9/1
    HOLIDAY: false
    MONTHWEEK:
      - 11-2
      - 11-3
  -
    SUMMARY: オープンキャンパス
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 4/1
    HOLIDAY: false
    MONTHWEEK:
      - 8-1
      - 8-2
  -
    SUMMARY: 卒論発表
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 9/1
    HOLIDAY: false
    MONTHWEEK:
      - 2-2
      - 2-3
    ORDER:
      AFTER:
        - 2/6
  -
    SUMMARY: 修論発表
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 9/1
    HOLIDAY: false
    MONTHWEEK:
      - 2-2
      - 2-3
    ORDER:
      AFTER:
        - 2/5
  -
    SUMMARY: 大学の推薦入試
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 4/1
    MONTHWEEK:
      - 12-1
    WDAY:
      - Sat
  -
    SUMMARY: 大学の編入試験
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 4/1
    MONTHWEEK:
      - 6-4
    WDAY:
      - Tue
  -
    SUMMARY: 大学の卒業式
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 4/1
    DATE:
      - 3/25
  -
    SUMMARY: 防災訓練
    CALENDAR: university
    INTERVAL: 365
    DURATION: 120
    TIMING:
      - 9/1
    MONTH:
      - 11
  -
    SUMMARY: 講義1
    CALENDAR: university
    INTERVAL: 7
    DURATION: 90
    TIMING:
      - 4/1
    HOLIDAY: false
    WDAY:
      - Fri
    VACATION_TERM:
      - 1/1-4/7
      - 7/31-3/31
  -
    SUMMARY: 講義2
    CALENDAR: university
    INTERVAL: 7
    DURATION: 90
    TIMING:
      - 4/1
    HOLIDAY: false
    WDAY:
      - Wed
    VACATION_TERM:
      - 1/1-4/7
      - 7/31-3/31
  -
    SUMMARY: 講義3
    CALENDAR: university
    INTERVAL: 7
    DURATION: 90
    TIMING:
      - 4/1
    HOLIDAY: false
    WDAY:
      - Tue
    VACATION_TERM:
      - 1/1-4/7
      - 7/31-3/31
  -
    SUMMARY: 講義4
    CALENDAR: university
    INTERVAL: 7
    DURATION: 90
    TIMING:
      - 4/1
    HOLIDAY: false
    WDAY:
      - Wed
    VACATION_TERM:
      - 2/7-3/31
      - 4/1-9/30
      - 12/25-1/3
  -
    SUMMARY: 講義5
    CALENDAR: university
    INTERVAL: 7
    DURATION: 90
    TIMING:
      - 4/1
    HOLIDAY: false
    WDAY:
      - Thu
    VACATION_TERM:
      - 2/7-3/31
      - 4/1-9/30
      - 12/25-1/3
  -
    SUMMARY: 大学の前期入試
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 4/1
    DATE:
      - 2/25
  -
    SUMMARY: 大学の後期入試
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 4/1
    DATE:
      - 3/12
  -
    SUMMARY: 大学の入学式
    CALENDAR: university
    INTERVAL: 365
    DURATION: 360
    TIMING:
      - 4/1
    DATE:
      - 4/8
  -
    SUMMARY: ミーティング1
    CALENDAR: gn
    DURATION: 120
    TIMING: successively
    INTERVAL: 14
    HOLIDAY: false
    HIDDEN_EVENTS: true
    VACATION_TERM:
      - 8/10-8/14
      - 12/25-1/3
    DEADLINE:
      - 2/5
  -
    SUMMARY: ミーティング2
    CALENDAR: gn
    DURATION: 120
    TIMING: successively
    INTERVAL: 14
    HOLIDAY: false
    HIDDEN_EVENTS: true
    VACATION_TERM:
      - 8/10-8/14
      - 12/25-1/3
  -
    SUMMARY: ミーティング3
    CALENDAR: new
    DURATION: 120
    TIMING: successively
    INTERVAL: 14
    HOLIDAY: false
    HIDDEN_EVENTS: true
    VACATION_TERM:
      - 8/10-8/14
      - 12/25-1/3
    DEADLINE:
      - 2/5
  -
    SUMMARY: ミーティング4
    CALENDAR: new
    DURATION: 120
    TIMING: successively
    INTERVAL: 14
    HOLIDAY: false
    HIDDEN_EVENTS: true
    VACATION_TERM:
      - 8/10-8/14
      - 12/25-1/3
  -
    SUMMARY: 進捗報告会3
    CALENDAR: net-mgr
    INTERVAL: 30
    DURATION: 120
    TIMING: successively
    HOLIDAY: false
    HIDDEN_EVENTS: true
    VACATION_TERM:
      - 8/10-8/14
      - 12/25-1/3
